### PR TITLE
modify image so gopher eyes are visible

### PR DESCRIPTION
**Pull request by campoy**
Signed-off-by: Francesc Campoy <campoy@golang.org>

### CODE REVIEW

**Comment by campoy** [comment]
Even after reading the documentation I still do not understand how to push this to staging.
Am I supposed to merge it to staging first? Can I even do that or do I need extra rights?

Please clarify this, it's quite confusing and annoying.

cc: @mcuadros @vmarkovtsev

**Comment by vmarkovtsev** [comment]
Not sure about staging - I see no point in it for the new content in the blog. The changes are easily tested locally.

So after I merged this PR, I created https://github.com/src-d/blog/releases/tag/v1.1.10 and it went live through CD.

**Comment by vmarkovtsev** [comment]
@campoy It appears that I've got admin rights here so I gave the write permissions to devrel team so that you should be able to merge now. At the same time you are supposed to be an admin - all leads are admins here. I guess your position is not fully set on GitHub, you need to consult with Máximo.

**Comment by dpordomingo** [comment]
I think that deploying in staging is a good way to validate all web sites (or to add a screenshot in the PR). Now that CD works like a charm, we could be benefited a lot of staging, and we could meet to find the best way to proceed.

From the current guidelines [guide/engineering/continuous-delivery.md#deploying-into-staging](https://github.com/src-d/guide/blob/master/engineering/continuous-delivery.md#deploying-into-staging)
> _Whenever staging branch is updated, drone automatically deploys it to Staging environment_

it's trying to explain that every new commit in staging causes a deploy into staging.
If you feel that the guides are not clear enough, please open an issue to keep it in mind now that documentation is a company priority. (PRs are welcomed too, for sure)

**Comment by campoy** [comment]
Basically my doubt is whether staging is a branch or a tag and what rights I need to have in order to do these.

**Comment by dpordomingo** [comment]
Staging is a branch.
I think you should need push privileges into src-d/blog repo. I think it should be granted by @mcuadros but now that @vmarkovtsev did some magic I think you can already do it.

**Comment by vmarkovtsev** [comment]
BTW @dpordomingo staging is completely independent of master and should not be merged, correct?

**Comment by dpordomingo** [comment]
- `staging` should be never merged over any other branch, specially never ever over `master`
- `master` can be merged over `staging` to update it with new things. When there are no other thing being tested in staging, `staging` branch can be reseyed from `master` or from any other branch.

I tried to explain it in the guide, so since there appeared that much doubts, I think you should help me to improve it in order to make it more clear.

**Comment by dpordomingo** [comment]
- `staging` should be never merged over any other branch, specially never ever over `master`
- `master` can be merged over `staging` to update it with new things. When there are no other thing being tested in staging, `staging` branch can be reseyed from `master` or from any other branch.

Does it answer your question @vmarkovtsev ?

I tried to explain it in the guide, so since there appeared that much doubts, I think you should help me to improve it in order to make it more clear.

**Comment by campoy** [comment]
Probably worth writing it down as a step by step on how to deploy something a change to staging then prod.

**Comment by dpordomingo** [comment]
Issue opened. Here is the link in case you want to follow its progress, or provide more feedback.
https://github.com/src-d/guide/issues/89

**Pull request merged**
