### PR TITLE
Logofix

### PR DESCRIPTION
**Pull request by vmarkovtsev**
screen shot 2018-10-26 at 16 13 07

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
@campoy I used the logo which Ricardo has created: https://github.com/src-d/artwork/blob/master/pga/README.md

**Comment by campoy** [comment]
DCO is missing.

**Comment by vmarkovtsev** [comment]
@campoy not required for source{d} employees.

**Comment by campoy** [comment]
Please, @vmarkovtsev do not merge your own PRs.
**This is not acceptable.**

According to the guide the DCO needs to be signed for every single contribution,
no matter whether the contributor is an employee or not.

**Comment by vmarkovtsev** [comment]
I signed the darn DCO and PR has been approved, so according to the guide I could merge it.

**Comment by vmarkovtsev** [comment]
@campoy

**Comment by vmarkovtsev** [comment]
image
@campoy

**Comment by mcuadros** [comment]
@vmarkovtsev This commit doesn't look as a signed-off commit at all:

```
commit 026e0b01ae0a88bb9b852ea76fb254cdf86d6870
Author: Vadim Markovtsev <vadim@sourced.tech>
Date:   Fri Oct 26 16:05:42 2018 +0200

    Update the pga announcement logo
```

Dismissing a validation is not the same as sing-off the commit, at all!

**Comment by campoy** [comment]
Vadim, you do realize that I'm just asking you to follow the rules. Right?

As @mcuadros indicated to you on slack, setting the DCO bot to pass doesn't mean you signed the DCO. We've removed the admin rights that allowed you to do so.

Lastly, please realize this is not a personal attack on you. You might want to reconsider your tone.

**Comment by vmarkovtsev** [comment]
@campoy I am sorry. As I already wrote Máximo in DM (also stated in #dev-machine-learning on Slack) that I honestly thought that it was OK to explicitly put the DCO agreement in the web UI. This is quite lame of me - also this bureaucracy has to be reviewed at some point.

**Pull request merged**
