### PR TITLE
Add Proteus post image

### PR DESCRIPTION
**Pull request by vmarkovtsev**
Img taken from https://pixabay.com/en/chameleon-animal-lizard-nature-zoo-1801225/
This chameleon was cut so that he looks at "Proteus" in the title.
Chameleon because he changes his look, too.

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
@erizocosmico OK?

**Comment by erizocosmico** [comment]
Why a chameleon?

**Comment by vmarkovtsev** [comment]
> Chameleon because he changes his look, too.

**Comment by erizocosmico** [comment]
Ok, we can set it. But still don't get what it has to do with proteus at all.

**Comment by vmarkovtsev** [comment]
The alternative was to find a free Ninja Turtles with Splinter image for "mutability".

**Pull request merged**
