### PR TITLE
Add the article about tabs and spaces

### PR DESCRIPTION
**Pull request by vmarkovtsev**

### CODE REVIEW

**Comment by curratore** [comment]
LGTM

**Comment by mcuadros** [comment]
LGTM

**Comment by mcuadros** [comment]
@vmarkovtsev what about having 4G instead of 4.000.000 in the table on article? Can be change that?

**Comment by vmarkovtsev** [comment]
Well, the Felipe doesn't have G or M - it's raw numbers; it's better to leave it as-is: when I change it to T, G and M it would be hard to compare (now it's relatively easy). Compare:

 language |      bytes      |   files   |     lines    |    mixed    |    spaces    |    tabs   
----------|----------------:|----------:|-------------:|------------:|-------------:|------------:
JavaScript|2,341,806,127,239|253,624,606|58,906,872,257|1,174,892,415|37,690,003,403|7,595,561,183
XML       |2,479,319,068,034| 56,930,249|41,546,961,517|  158,432,895|35,423,202,049|2,794,001,951
PHP       |1,069,618,433,872|163,013,141|31,515,962,120|1,464,277,369|15,795,790,172|7,712,560,467

and

 language |      bytes      |   files   |     lines    |    mixed    |    spaces    |    tabs   
----------|----------------:|----------:|-------------:|------------:|-------------:|------------:
JavaScript|2.3T|253M|59G|1G|37G|7.6G
XML       |2.5T| 59M|41G|  158M|35G|2.8G
PHP       |1.0T|163M|31G|1.5G|16G|8G

**Pull request merged**
