### PR TITLE
Crop images from Moscow post

### PR DESCRIPTION
**Pull request by warenlg**

### CODE REVIEW

**Comment by warenlg** [comment]
yes, I don t understand why the --resize 600x350 commad sometimes gave me such an approximation

**Comment by vmarkovtsev** [comment]
Did you use imagemagick?

**Comment by vmarkovtsev** [comment]
Besides @warenlg why did you resize? I guess 600px will look like shit on my retina. Could you try not to resize but rather crop bottom and top?

**Comment by warenlg** [comment]
its convert crop command yes, It's not a way to do it ?

**Comment by vmarkovtsev** [comment]
Consider lossless jpeg crop

**Comment by warenlg** [comment]
yes let me dig into it again

**Comment by warenlg** [comment]
Cropped with Xnconvert (from the list)
Some are bigger than others but the aspect ratio stays the same

**Pull request merged**
