### PR TITLE
Fix makefile dependencies management

### PR DESCRIPTION
**Pull request by aslafy-z**
- Fix hugo dependency: ensure `hugo` is newer than it's tarball
- Bind hugo to `0.0.0.0`
- Do not update lockfile on make

This is needed for #254

### CODE REVIEW

**Comment by bzz** [comment]
Hey @aslafy-z thank you for proposing improvements!

Sorry if it will take some time to accept them, please check https://github.com/src-d/blog/pull/252#issuecomment-433404798 for context.

**Comment by bzz** [comment]
\cc @dpordomingo for a quick look

**Comment by dpordomingo** [comment]
Many thanks, @aslafy-z for helping us to improve the development process on blog.
We're currently working in a migration to [ghost](https://ghost.org/), so we aren't adding new features to current one.
I'll keep this PR opened just in case we keep using the current blog, so we'll consider your nice suggestion.

**Comment by vcoisne** [comment]
Migrated to Ghost. Thanks anyways @aslafy-z

**Pull request closed without merging**
