### PR TITLE
post content styles

### PR DESCRIPTION
**Pull request by erizocosmico**

### CODE REVIEW

**Comment by erizocosmico** [comment]
Can be reviewed @Serabe @dpordomingo @marnovo 

Basically, same styles as the project page. Just, in the blog.

**Comment by vmarkovtsev** [comment]
How do we use LaTeX now without mathjax?

**Comment by erizocosmico** [comment]
MathJax was removed from specific posts and moved globally. You can use it like you did before, just not including scripts in every post.
On Mon, 24 Jul 2017 at 10:05, Vadim Markovtsev <notifications@github.com<mailto:notifications@github.com>> wrote:

How do we use LaTeX now without mathjax?

**Comment by Serabe** [comment]
Closing as #123 was merged into `new-design` branch.

Thank you!

**Pull request closed without merging**
